### ISSUE TITLE
NoMethodError: undefined method `to_millis' 

### ISSUE THREAD

**Issue by calmyournerves** [bsm/datadog-notifications#6]
Hey there

Tried to get this running, but it crashed:

```
NoMethodError: undefined method `to_millis' for #<Datadog::Notifications::Plugins::ActionController:0x00000002f418a0>
```

Looking at `lib/datadog/notifications/plugins/action_controller.rb` I was wondering, where should `to_millis` come from? Could it just be dropped as the Rails instrumentation already returns milliseconds?

**Comment by dim** [comment]
Good catch, released fix as https://github.com/bsm/datadog-notifications/releases/tag/v0.4.4. Thanks!

**Comment by calmyournerves** [comment]
Cool, thank you!
